name: webapp_workflow
description: API model implementation.
version: 0.4.0
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  intl: ^0.19.0
  json_string: ^3.0.1

  flutter:
    sdk: flutter
  
  webapp_model:
    path: ../webapp_model

  webapp_ui_commons:
    path: ../webapp_ui_commons

  webapp_utils:
    path: ../webapp_utils


dev_dependencies:
  test:
  lints: ^5.0.0

