name: webapp_components
description: API model implementation.
version: 0.4.2
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  webapp_model:
    path: ../webapp_model

  webapp_ui_commons:
    path: ../webapp_ui_commons

  webapp_utils:
    path: ../webapp_utils

  list_picker: ^1.1.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  synchronized: ^3.0.0
  syncfusion_flutter_pdf: ^27.2.2
  file_picker: ^8.0.5
  flutter_dropzone: ^4.0.1
  
  flutter:
    sdk: flutter
dev_dependencies:
  test:
  lints: ^5.0.0
  build_runner: ^2.3.3
