name: webapp_model
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.4.1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  # webapp_components:
  #   path: ../webapp_components
  webapp_ui_commons:
    path: ../webapp_ui_commons
  webapp_utils:
    path: ../webapp_utils
  
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  # sci_tercen_client:
    # path: ../../../sci_tercen_client/sci_tercen_client
  sci_tercen_client:
    git:
      ref: 1.4.12
      url: https://github.com/tercen/sci_tercen_client
      path: sci_tercen_client
  


dev_dependencies:
  build_runner: ^2.3.3



